export enum Role {
  CLAIMANT = "CLAIMANT",
  MANAGER = "MANAGER",
  FINANCE = "FINANCE",
}

export enum ClaimStatus {
  DRAFT = "DRAFT",
  PENDING_MANAGER = "PENDING_MANAGER",
  PENDING_FINANCE = "PENDING_FINANCE",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum ApprovalDecision {
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum AuditAction {
  CREATE_CLAIM = "CREATE_CLAIM",
  UPDATE_CLAIM = "UPDATE_CLAIM",
  SUBMIT_CLAIM = "SUBMIT_CLAIM",

  APPROVE_CLAIM = "APPROVE_CLAIM",
  REJECT_CLAIM = "REJECT_CLAIM",

  ADD_ITEM = "ADD_ITEM",
  UPDATE_ITEM = "UPDATE_ITEM",
  DELETE_ITEM = "DELETE_ITEM",

  UPLOAD_ATTACHMENT = "UPLOAD_ATTACHMENT",
}

export enum NotificationType {
  CLAIM_SUBMITTED = "CLAIM_SUBMITTED",
  CLAIM_PENDING_APPROVAL = "CLAIM_PENDING_APPROVAL",
  CLAIM_APPROVED = "CLAIM_APPROVED",
  CLAIM_REJECTED = "CLAIM_REJECTED",
}